//Autogenerated "Paste JSON as Classes"
using System;
using System.Collections.Generic;

namespace TeleReposter
{
    public class Resource
    {
        public string name { get; set; }
        public string chatId { get; set; }
        public string logChatId { get; set; }
    }

    public class LastReposted
    {
        public string resource { get; set; }
        public string itemId { get; set; }
        public DateTime dateTime{ get; set; }
    }

    public class MediaResourcesConfig
    {
        public List<Resource> resources { get; set; }
        public List<LastReposted> lastReposted { get; set; }
        public Settings settings { get; set; }
    }

    public class Settings
    {
        public long chatId { get; set; }
        public TimerPeriod timerPeriod { get; set; }
        public int contentCount { get; set; }
    }

    public class TimerPeriod
    {
        public int hours { get; set; }
        public int minutes { get; set; }
        public int seconds { get; set; }
    }
}
